name: Omnihub
favicon: null
layout_spectrum: 0.506707765860483
typography_spectrum: 0.5406408975832164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.30067825759761035
  lightness: 0.6368610560894012
  saturation: 0.9488224831875414
  rhythmicContrast: 0.4159324432257563
purpose: []
